<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="B2C Flight" duration-ms="39710" started-at="2018-09-03T06:12:22Z" finished-at="2018-09-03T06:13:02Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="39710" started-at="2018-09-03T06:12:22Z" finished-at="2018-09-03T06:13:02Z">
      <class name="com.flight.pages.testcases.Workflow">
        <test-method status="PASS" signature="testdataread()[pri:0, instance:com.flight.pages.testcases.Workflow@204f30ec]" name="testdataread" is-config="true" duration-ms="234" started-at="2018-09-03T06:12:23Z" finished-at="2018-09-03T06:12:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdataread -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.flight.pages.testcases.Workflow@204f30ec]" name="setup" is-config="true" duration-ms="15485" started-at="2018-09-03T06:12:23Z" finished-at="2018-09-03T06:12:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="multicityworkflow()[pri:0, instance:com.flight.pages.testcases.Workflow@204f30ec]" name="multicityworkflow" duration-ms="23709" started-at="2018-09-03T06:12:38Z" finished-at="2018-09-03T06:13:02Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.flight.pages.SearchPage.multicityselector(SearchPage.java:371)
at com.flight.pages.testcases.Workflow.multicityworkflow(Workflow.java:145)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multicityworkflow -->
      </class> <!-- com.flight.pages.testcases.Workflow -->
    </test> <!-- Test -->
  </suite> <!-- B2C Flight -->
</testng-results>
